### ISSUE TITLE
Neproběhne K4 export

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1075]
Nejde exportovat K4 export. Ale v exportních složkách se uuid objeví, uvnitř je jen log.
![obrazek](https://user-images.githubusercontent.com/13831946/73086852-b1c84300-3ed1-11ea-9502-b7b8f0498299.png)

**Comment by krizovj** [comment]
Pod monografii s NDK stranami jsem zkusila založit tři NDK kapitoly a zkusila jsem to vyexportovat jako Kramerius export. Vyhodilo mi to neočekávanou chybu:

Exception Report

Message java.lang.NumberFormatException: For input string: ""

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

javax.servlet.ServletException: java.lang.NumberFormatException: For input string: ""
	org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:489)
	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	cz.cas.lib.proarc.authentication.ProarcAuthFilter.securedContent(ProarcAuthFilter.java:72)
	cz.cas.lib.proarc.authentication.ProarcAuthFilter.doFilter(ProarcAuthFilter.java:50)
	cz.cas.lib.proarc.webapp.server.EditorServletConfiguration.doFilter(EditorServletConfiguration.java:96)
Root Cause

java.lang.NumberFormatException: For input string: ""
	java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	java.lang.Integer.parseInt(Integer.java:592)
	java.lang.Integer.parseInt(Integer.java:615)
	cz.cas.lib.proarc.common.export.Kramerius4Export.getNumber(Kramerius4Export.java:745)
	cz.cas.lib.proarc.common.export.Kramerius4Export.getChildren(Kramerius4Export.java:717)
	cz.cas.lib.proarc.common.export.Kramerius4Export.getChildren(Kramerius4Export.java:705)
	cz.cas.lib.proarc.common.export.Kramerius4Export.transformRelation2Kramerius(Kramerius4Export.java:645)
	cz.cas.lib.proarc.common.export.Kramerius4Export.processRelsExt(Kramerius4Export.java:573)
	cz.cas.lib.proarc.common.export.Kramerius4Export.exportDatastreams(Kramerius4Export.java:424)
	cz.cas.lib.proarc.common.export.Kramerius4Export.exportPid(Kramerius4Export.java:303)
	cz.cas.lib.proarc.common.export.Kramerius4Export.export(Kramerius4Export.java:159)
	cz.cas.lib.proarc.webapp.server.rest.ExportResource.kramerius4(ExportResource.java:159)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	cz.cas.lib.proarc.authentication.ProarcAuthFilter.securedContent(ProarcAuthFilter.java:72)
	cz.cas.lib.proarc.authentication.ProarcAuthFilter.doFilter(ProarcAuthFilter.java:50)
	cz.cas.lib.proarc.webapp.server.EditorServletConfiguration.doFilter(EditorServletConfiguration.java:96)
Note The full stack trace of the root cause is available in the server logs.


[object Object]
Status: -90
Query: { "operationType":"add", "dataSource":"isc_ExportDataSource_0", "data":null, "requestId":"isc_ExportDataSource_0$627176", "$135x":null, "useStrictJSON":null, "$135v":null, "fallbackToEval":false, "textMatchStyle":"exact", "$178g":true, "showPrompt":false, "lastClientEventThreadCode":"MUP9", "$135w":null, "parentNode":null, "httpMethod":"POST", "useSimpleHttp":true, "httpHeaders":{ "Accept":"application/json", "Accept-Language":"cs" }, "promptStyle":"dialog", "$135u":null, "bypassCache":true, "originalData":{ "pid":[ "uuid:28621fd9-ced0-4603-b958-994168d00465" ], "policy":"policy:public" }, "unconvertedDSRequest":{ "operationType":"add", "dataSource":"isc_ExportDataSource_0", "data":{ "pid":[ "uuid:28621fd9-ced0-4603-b958-994168d00465" ], "policy":"policy:public" }, "requestId":"isc_ExportDataSource_0$627176", "$135x":null, "useStrictJSON":null, "$135v":null, "fallbackToEval":false, "textMatchStyle":"exact", "$178g":true, "showPrompt":false, "lastClientEventThreadCode":"MUP9", "$135w":null, "parentNode":null, "httpMethod":"POST", "useSimpleHttp":true, "httpHeaders":{ "Accept":"application/json", "Accept-Language":"cs" }, "promptStyle":"dialog", "$135u":null, "bypassCache":true, "originalData":{ "pid":[ "uuid:28621fd9-ced0-4603-b958-994168d00465" ], "policy":"policy:public" } }, "dataProtocol":"postParams", "isRestRequest":true, "dataFormat":"json", "$85o":1581329063614, "useHttpProxy":null, "actionURL":"https://proarc-test.libj.cas.cz/proarc/rest/v1/export/kramerius4", "params":{ "pid":[ "uuid:28621fd9-ced0-4603-b958-994168d00465" ], "policy":"policy:public", "_operationType":"add", "_textMatchStyle":"exact", "_dataSource":"isc_ExportDataSource_0", "isc_metaDataPrefix":"_", "isc_dataFormat":"json" }, "callback":{ "target":{ "ID":"isc_ExportDataSource_0", "dataFormat":"json", "requestProperties":{ "useSimpleHttp":true, "httpHeaders":{ "Accept":"application/json", "Accept-Language":"cs" }, "promptStyle":"dialog" }, "fields":[ { "name":"target", "type":"text", "$61":true, "$62":{ "validators":[ { "type":"isString", "typeCastValidator":true, "_generated":true, "$174l":true, "stopIfFalse":true, "defaultErrorMessage":null } ], "name":"text", "$68":true }, "title":"Target", "$76s":true } ], "operationBindings":[ { "operationType":"add", "dataProtocol":"postParams", "requestProperties":{ "httpMethod":"POST" } } ], "dataURL":"https://proarc-test.libj.cas.cz/proarc/rest/v1/export/kramerius4", "jsonPrefix":"", "jsonSuffix":"", "recordXPath":"/response/data" } }, "_dsRequest":{ "operationType":"add", "dataSource":"isc_ExportDataSource_0", "data":{ "pid":[ "uuid:28621fd9-ced0-4603-b958-994168d00465" ], "policy":"policy:public", "_operationType":"add", "_textMatchStyle":"exact", "_dataSource":"isc_ExportDataSource_0", "isc_metaDataPrefix":"_", "isc_dataFormat":"json" }, "requestId":"isc_ExportDataSource_0$627176", "$135x":null, "useStrictJSON":null, "$135v":null, "fallbackToEval":false, "textMatchStyle":"exact", "$178g":true, "showPrompt":false, "lastClientEventThreadCode":"MUP9", "$135w":null, "parentNode":null, "httpMethod":"POST", "useSimpleHttp":true, "httpHeaders":{ "Accept":"application/json", "Accept-Language":"cs" }, "promptStyle":"dialog", "$135u":null, "bypassCache":true, "originalData":{ "pid":[ "uuid:28621fd9-ced0-4603-b958-994168d00465" ], "policy":"policy:public" }, "unconvertedDSRequest":{ "operationType":"add", "dataSource":"isc_ExportDataSource_0", "data":{ "pid":[ "uuid:28621fd9-ced0-4603-b958-994168d00465" ], "policy":"policy:public" }, "requestId":"isc_ExportDataSource_0$627176", "$135x":null, "useStrictJSON":null, "$135v":null, "fallbackToEval":false, "textMatchStyle":"exact", "$178g":true, "showPrompt":false, "lastClientEventThreadCode":"MUP9", "$135w":null, "parentNode":null, "httpMethod":"POST", "useSimpleHttp":true, "httpHeaders":{ "Accept":"application/json", "Accept-Language":"cs" }, "promptStyle":"dialog", "$135u":null, "bypassCache":true, "originalData":{ "pid":[ "uuid:28621fd9-ced0-4603-b958-994168d00465" ], "policy":"policy:public" } }, "dataProtocol":"postParams", "isRestRequest":true, "dataFormat":"json", "$85o":1581329063614, "useHttpProxy":null }, "transport":"xmlHttpRequest", "serverOutputAsString":true, "suppressAutoDraw":true, "$185x":"https://proarc-test.libj.cas.cz/proarc/rest/v1/export/kramerius4", "promptCursor":"progress", "useCursorTracker":false, "cursorTrackerConstructor":"Img", "cursorTrackerProperties":{ "src":"[SKINIMG]shared/progressCursorTracker.gif", "size":16, "offsetX":12, "offsetY":0 }, "operation":{ "ID":"custom", "type":"rpc" }, "transactionNum":177 }



Nevím, jestli to souvisí s tímto issue, nebo spíš s tímhle: https://github.com/proarc/proarc/issues/289
