### ISSUE TITLE
invalid XML character export

### ISSUE THREAD

**Issue by PetrKotynek** [proarc/proarc#1695]
Připojjuji logy atd... PK

přeposílám popis chyby a screenshot chybové hlášky, na kterou narazili v OZČ při zakládání ečlánku v proarc-ozc. Mně se to nedaří replikovat, podíváš se na to, prosím?

[log.zip](https://github.com/user-attachments/files/15951545/log.zip)
![Chyba PA](https://github.com/proarc/proarc/assets/37083676/4b31bcfd-cc79-4bb4-8e92-9da087e6c20d)
[uuid_solr.txt](https://github.com/user-attachments/files/15951547/uuid_solr.txt)

**Comment by SykoraLukas** [comment]
Co se s daným objektem dělo? Co je cílem? Pošlete mi prosím FOXML objektu uuid:0b5452f1-ed98-4684-8ffd-1fb029935994.

Jak vypadá objekt uuid:0b5452f1-ed98-4684-8ffd-1fb029935994 v SOLRu Search? Poslal jsem zobrazení jiného záznamu.
Podle Logů vidím, že to Kateřina Neradová ráno kolem šesté objekt založila a poté uživatel fkdigi smazal v 8:44.

**Comment by kerschfilip** [comment]
Problém je, že jde založit nový prázdný e-článek, ale potom co se vyplní všechna pole  ve formuláři, tak to nejde uložit - uživateli se zobrazuje výše uvedená chyba.

Zkoušel jsem to řešit tak, že jsem se díval, jaká chyba mi vypadne při FOXML exportu čísla - bylo tam `[org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 708; Character reference "&#56256" is an invalid XML character.]] with root cause...` ve vztahu právě k uuid:0b5452f1-ed98-4684-8ffd-1fb029935994. Skrze UI se zdálo, že je ten ečlánek uuid:0b5452f1-ed98-4684-8ffd-1fb029935994 nějak poškozený, zkusil jsem ho tedy smazat, což mi prošlo v pohodě. Problém to ale evidentně nevyřešilo :/

**Comment by PetrKotynek** [comment]
Ten uuid se nenasel
![zaznam](https://github.com/proarc/proarc/assets/37083676/1d4d8db0-2c6d-4a08-85de-dbf49cc98484)

**Comment by SykoraLukas** [comment]
To, že se nenašel je správně, pokud ho Filip smazal.

Které pole tam hází chybu? Vypadá to na špatnou hodnotu v nějakém poli. Jak vypadá real-time generované xml?

**Comment by PetrKotynek** [comment]
fox od dalsiho zaznamu s chybou PK
[dalsi.txt](https://github.com/user-attachments/files/15952111/dalsi.txt)
[dissemination.zip](https://github.com/user-attachments/files/15952119/dissemination.zip)

**Comment by SykoraLukas** [comment]
Chyba není v aplikaci ale ve vašich datech. 

Viz: Č􀆽eští􀆴 Elfové v souboru dissemination.zip - smažte tyto nevalidní znaky a bude vše v pořádku. Nejspíše budete muset založit znovu a původní soubory smazat

**Comment by kerschfilip** [comment]
OK, moc díky!

Chyba vznikla nejspíš při kopírování z PDF, objekt se nám povedlo založit i se všemi daty, issue zavírám

**Comment by SykoraLukas** [comment]
Nejspíše bylo nastavené jiné kodovaní pro daný abstrakt, proto se po vložení do MODSU (kodovani UTF8) špatně transformovala hodnota.
